cu_cp:
  amf:
    addr: 10.53.1.2
    port: 38412
    bind_addr: 10.53.1.1
    supported_tracking_areas:
      - tac: 7
        plmn_list:
          - plmn: "00101"
            tai_slice_support_list:
              - sst: 1
  inactivity_timer: 7200
  e1ap:
    bind_addr: 127.0.20.1
  f1ap:
    bind_addr: 127.0.10.1

log:
  filename: /tmp/cu_cp_zmq.log
  all_level: warning
