cu_up:
  e1ap:
    cu_cp_addr: 127.0.20.1
    bind_addr: 127.0.20.2
  ngu:
    socket:
      -
        bind_addr: 10.53.1.1
  f1u:
    socket:
      -
        bind_addr: 127.0.10.1

log:
  filename: /tmp/cu_up_zmq.log
  all_level: warning
