#!/bin/bash
# start ZMQ setup with 16 UE(s)
# run each command in a separate terminal

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRSRAN_PROJECT="$SCRIPT_DIR/../srsRAN_Project/build/apps"
SRSRAN_4G="$SCRIPT_DIR/../srsRAN_4G/build/srsue/src"
CONFIGS="$SCRIPT_DIR/../configs"

echo "start in separate terminals:"
echo ""
echo "1. CU-CP:"
echo "   sudo $SRSRAN_PROJECT/cu_cp/srscucp -c $CONFIGS/zmq_split/cu_cp_zmq.yml"
echo ""
echo "2. CU-UP:"
echo "   sudo $SRSRAN_PROJECT/cu_up/srscuup -c $CONFIGS/zmq_split/cu_up_zmq.yml"
echo ""
echo "3. DU:"
echo "   sudo $SRSRAN_PROJECT/du/srsdu -c $CONFIGS/zmq_split/du_zmq.yml"
echo ""
echo "4. GNU Radio broker:"
echo "   python3 $CONFIGS/zmq/gnuradio_broker_16ue.py"
echo ""
echo "5. UE1:"
echo "   sudo $SRSRAN_4G/srsue $CONFIGS/zmq/ue1_zmq.conf"
echo ""
echo "6. UE2:"
echo "   sudo $SRSRAN_4G/srsue $CONFIGS/zmq/ue2_zmq.conf"
echo ""
echo "7. UE3:"
echo "   sudo $SRSRAN_4G/srsue $CONFIGS/zmq/ue3_zmq.conf"
echo ""
echo "8. UE4:"
echo "   sudo $SRSRAN_4G/srsue $CONFIGS/zmq/ue4_zmq.conf"
echo ""
echo "9. UE5:"
echo "   sudo $SRSRAN_4G/srsue $CONFIGS/zmq/ue5_zmq.conf"
echo ""
echo "10. UE6:"
echo "   sudo $SRSRAN_4G/srsue $CONFIGS/zmq/ue6_zmq.conf"
echo ""
echo "11. UE7:"
echo "   sudo $SRSRAN_4G/srsue $CONFIGS/zmq/ue7_zmq.conf"
echo ""
echo "12. UE8:"
echo "   sudo $SRSRAN_4G/srsue $CONFIGS/zmq/ue8_zmq.conf"
echo ""
echo "13. UE9:"
echo "   sudo $SRSRAN_4G/srsue $CONFIGS/zmq/ue9_zmq.conf"
echo ""
echo "14. UE10:"
echo "   sudo $SRSRAN_4G/srsue $CONFIGS/zmq/ue10_zmq.conf"
echo ""
echo "15. UE11:"
echo "   sudo $SRSRAN_4G/srsue $CONFIGS/zmq/ue11_zmq.conf"
echo ""
echo "16. UE12:"
echo "   sudo $SRSRAN_4G/srsue $CONFIGS/zmq/ue12_zmq.conf"
echo ""
echo "17. UE13:"
echo "   sudo $SRSRAN_4G/srsue $CONFIGS/zmq/ue13_zmq.conf"
echo ""
echo "18. UE14:"
echo "   sudo $SRSRAN_4G/srsue $CONFIGS/zmq/ue14_zmq.conf"
echo ""
echo "19. UE15:"
echo "   sudo $SRSRAN_4G/srsue $CONFIGS/zmq/ue15_zmq.conf"
echo ""
echo "20. UE16:"
echo "   sudo $SRSRAN_4G/srsue $CONFIGS/zmq/ue16_zmq.conf"
echo ""

echo "after all UEs connected, add routes:"
echo "sudo ip netns exec ue1 ip route add default via 10.45.1.1 dev tun_srsue"
echo "sudo ip netns exec ue2 ip route add default via 10.45.1.1 dev tun_srsue"
echo "sudo ip netns exec ue3 ip route add default via 10.45.1.1 dev tun_srsue"
echo "sudo ip netns exec ue4 ip route add default via 10.45.1.1 dev tun_srsue"
echo "sudo ip netns exec ue5 ip route add default via 10.45.1.1 dev tun_srsue"
echo "sudo ip netns exec ue6 ip route add default via 10.45.1.1 dev tun_srsue"
echo "sudo ip netns exec ue7 ip route add default via 10.45.1.1 dev tun_srsue"
echo "sudo ip netns exec ue8 ip route add default via 10.45.1.1 dev tun_srsue"
echo "sudo ip netns exec ue9 ip route add default via 10.45.1.1 dev tun_srsue"
echo "sudo ip netns exec ue10 ip route add default via 10.45.1.1 dev tun_srsue"
echo "sudo ip netns exec ue11 ip route add default via 10.45.1.1 dev tun_srsue"
echo "sudo ip netns exec ue12 ip route add default via 10.45.1.1 dev tun_srsue"
echo "sudo ip netns exec ue13 ip route add default via 10.45.1.1 dev tun_srsue"
echo "sudo ip netns exec ue14 ip route add default via 10.45.1.1 dev tun_srsue"
echo "sudo ip netns exec ue15 ip route add default via 10.45.1.1 dev tun_srsue"
echo "sudo ip netns exec ue16 ip route add default via 10.45.1.1 dev tun_srsue"
