cu_up:
  e1ap:
    cu_cp_addr: 127.0.21.1
    bind_addr: 127.0.21.2
  ngu:
    socket:
      -
        bind_addr: 10.53.1.3
  f1u:
    socket:
      -
        bind_addr: 127.0.11.1

log:
  filename: /tmp/cu_up2_zmq.log
  all_level: warning
